name: Deploy Brcris-Nextjs

on:
  push:
    branches:
      - main

env:
  HOST_ELASTIC: ${{secrets.HOST_ELASTIC}}
  API_KEY: ${{secrets.API_KEY}}
  MAIL_HOST: ${{secrets.MAIL_HOST}}
  MAIL_SENDER: ${{secrets.MAIL_SENDER}}
  MAIL_PASSWORD: ${{secrets.MAIL_PASSWORD}}
  MAIL_PORT: ${{secrets.MAIL_PORT}}
  MAIL_RECIPIENT: ${{secrets.MAIL_RECIPIENT}}
  RECAPTCHA_SECRET_KEY: ${{secrets.RECAPTCHA_SECRET_KEY}}
  VIVO_URL_BASE: ${{secrets.VIVO_URL_BASE}}
  VIVO_URL_ITEM_BASE: ${{secrets.VIVO_URL_ITEM_BASE}}
  BRCRIS_HOST_BASE: ${{vars.BRCRIS_HOST_BASE}}

jobs:
  test:
    runs-on: [self-hosted, Linux, x64, runner-iroxa]
    environment:
      name: test
      url: 'http://codich1.ibict.br:8086/'

    steps:
      - uses: actions/checkout@v3
      - run: |
          sh scripts/deploy.sh

  homol:
    runs-on: [self-hosted, Linux, x64, runner-homol]
    environment:
      name: homol
      url: 'http://172.16.20.48:3000/'
    env:
      NODE_TLS_REJECT_UNAUTHORIZED: 0
    steps:
      - uses: actions/checkout@v3
      - run: |
          sh scripts/deploy.sh

  prod:
    runs-on: [self-hosted, Linux, x64, runner-pacova]
    environment:
      name: prod
      url: 'https://brcris.ibict.br'

    steps:
      - uses: actions/checkout@v3
      - run: |
          sh scripts/deploy.sh
