name: Deploy Brcris-Nextjs

on:
  push:
    branches:
      - main

env:
  HOST_ELASTIC: ${{secrets.HOST_ELASTIC}}
  API_KEY: ${{secrets.API_KEY}}
  MAIL_HOST: ${{secrets.MAIL_HOST}}
  MAIL_SENDER: ${{secrets.MAIL_SENDER}}
  MAIL_PASSWORD: ${{secrets.MAIL_PASSWORD}}
  MAIL_PORT: ${{secrets.MAIL_PORT}}
  MAIL_RECIPIENT: ${{secrets.MAIL_RECIPIENT}}
  RECAPTCHA_SECRET_KEY: ${{secrets.RECAPTCHA_SECRET_KEY}}

jobs:
  test:
    runs-on: [self-hosted, Linux, x64, runner-iroxa]
    environment:
      name: test
      url: 'http://172.16.16.79:3000'

    steps:
      - uses: actions/checkout@v3
      - run: |
          sh scripts/deploy.sh

  # prod:
  #   runs-on: [self-hosted, Linux, x64, runner-peroba]
  #   environment:
  #     name: prod
  #     url: 'https://api-oasisbr.ibict.br/api/v1/'

  # steps:
  #   - uses: actions/checkout@v3
  #   - run: |
  #       sh scripts/deploy.sh
